#!/usr/bin/env bash
# Auto-generate README.md from TIL directory structure.

set -euo pipefail

TIL_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
README="$TIL_ROOT/README.md"

# Count total TILs
total=0
for dir in "$TIL_ROOT"/*/; do
  [ -d "$dir" ] || continue
  name="$(basename "$dir")"
  [[ "$name" == .* || "$name" == "scripts" ]] && continue
  count=$(find "$dir" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')
  total=$((total + count))
done

# Header
cat > "$README" <<EOF
# TIL (Today I Learned)

> ${total} TILs and counting...

A collection of short, useful things I've learned day to day.
Each entry is kept short -- just the command/concept and a working example.

---

EOF

# Table of contents
for dir in "$TIL_ROOT"/*/; do
  [ -d "$dir" ] || continue
  name="$(basename "$dir")"
  [[ "$name" == .* || "$name" == "scripts" ]] && continue
  count=$(find "$dir" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')
  [ "$count" -eq 0 ] && continue
  echo "- [${name}](#${name}) (${count})" >> "$README"
done

echo "" >> "$README"
echo "---" >> "$README"
echo "" >> "$README"

# Entries by category
for dir in "$TIL_ROOT"/*/; do
  [ -d "$dir" ] || continue
  name="$(basename "$dir")"
  [[ "$name" == .* || "$name" == "scripts" ]] && continue
  files=("$dir"*.md)
  # Skip if glob didn't match anything
  [ -e "${files[0]}" ] || continue

  echo "## ${name}" >> "$README"
  echo "" >> "$README"

  for f in "${files[@]}"; do
    # Try to extract the first H1 as the title
    title=$(grep -m1 '^# ' "$f" 2>/dev/null | sed 's/^# //' || true)
    if [ -z "$title" ]; then
      # Fall back to filename with dashes replaced by spaces
      title="$(basename "$f" .md | tr '-' ' ')"
    fi
    relpath="${f#"$TIL_ROOT"/}"
    echo "- [${title}](${relpath})" >> "$README"
  done

  echo "" >> "$README"
done

cat >> "$README" <<'EOF'
---

*Auto-generated by [scripts/build_readme.sh](scripts/build_readme.sh)*
EOF

echo "README.md updated: ${total} TILs"
